---
record_0:
  Title: Opening Speech
  Start time: 11/29/2013 9:30
  Stop time: 11/29/2013 9:45
  Room: 'D1F Conference Room '
  Abstract: '-'
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Yuan Sheng
  Speaker introduction: 
record_1:
  Title: Keynote
  Start time: 11/29/2013 9:45
  Stop time: 11/29/2013 10:15
  Room: 'D1F Conference Room '
  Abstract: '-'
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: '-'
  Speaker introduction: 
record_2:
  Title: Seminar
  Start time: 11/29/2013 10:15
  Stop time: 11/29/2013 10:30
  Room: 
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_3:
  Title: SW Defined Network
  Start time: 11/29/2013 10:30
  Stop time: 11/29/2013 11:15
  Room: A3F Gemini (18)
  Abstract: |-
    Basic Functionality
    -SDN Service Chaining
    Benefits to Customer
    -Better usage of VAS, Value Added Services using dynamic chaining
    -SDN providing dynamic network connectivity for EPC services in cloud
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Lasse Olsson & Richard Wang
  Speaker introduction: 
record_4:
  Title: Ericsson Cloud System and Management
  Start time: 11/29/2013 11:15
  Stop time: 11/29/2013 12:00
  Room: A3F Gemini (18)
  Abstract: '-'
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Haibin Chu & Xuejun Li
  Speaker introduction: 
record_5:
  Title: VoLTE/SRVCC
  Start time: 11/29/2013 10:30
  Stop time: 11/29/2013 11:15
  Room: A3F Taurus (18)
  Abstract: 
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Karen Zhen& Xiao Li & Eva Li
  Speaker introduction: 
record_6:
  Title: UDM/UPG
  Start time: 11/29/2013 11:15
  Stop time: 11/29/2013 12:00
  Room: A3F Taurus (18)
  Abstract: 
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Arthur Wen
  Speaker introduction: 
record_7:
  Title: Heterogeneous Network
  Start time: 11/29/2013 10:30
  Stop time: 11/29/2013 11:15
  Room: A4F Galaxy (38)
  Abstract: 
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Paul??s team
  Speaker introduction: 
record_8:
  Title: WiFi Integration
  Start time: 11/29/2013 11:15
  Stop time: 11/29/2013 12:00
  Room: A4F Galaxy (38)
  Abstract: 
  Column span: '1'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Judy Gan & Peter Chen
  Speaker introduction: 
record_9:
  Title: Lunch Break
  Start time: 11/29/2013 12:00
  Stop time: 11/29/2013 13:00
  Room: '-'
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_10:
  Title: Demo
  Start time: 11/29/2013 13:00
  Stop time: 11/29/2013 13:00
  Room: 
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_11:
  Title: Ericsson LTE Broadcasting
  Start time: 11/29/2013 13:15
  Stop time: 11/29/2013 14:00
  Room: E3F Tai Mountain (20)
  Abstract: Ericsson LTE Broadcast enables new revenue models for premium media content
    offering exceptional user experience while efficiently utilizing available LTE
    spectrum and operators?? network resources??
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Shaheer Jamal & Benjamin Li
  Speaker introduction: 
record_12:
  Title: VoLTE on TD-LTE
  Start time: 11/29/2013 13:00
  Stop time: 11/29/2013 13:20
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_13:
  Title: LTE/Wifi integration by Real Time traffic steering
  Start time: 11/29/2013 13:20
  Stop time: 11/29/2013 13:40
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_14:
  Title: WiFi/3gpp integration by ANDSF
  Start time: 11/29/2013 13:40
  Stop time: 11/29/2013 14:00
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_15:
  Title: Smart MBB
  Start time: 11/29/2013 14:00
  Stop time: 11/29/2013 14:20
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_16:
  Title: TDD/FDD interworking
  Start time: 11/29/2013 14:20
  Stop time: 11/29/2013 14:40
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_17:
  Title: 'NLOS Microwave @ 23 GHz  '
  Start time: 11/29/2013 14:40
  Stop time: 11/29/2013 15:00
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_18:
  Title: Multi Screen TV Portal
  Start time: 11/29/2013 15:00
  Stop time: 11/29/2013 15:20
  Room: Wild-Center
  Abstract: |-
    Basic Functionality
    -Easy access to content
    -A unified television environment
    -One stop shop
    -A complete ecosystem
    -A streamlined consumer experience
    Benefits to Customer
    -One Solution: Any content, any network, any device, value-added services
    -Enhance the viewing experience through the 2nd screen without disturbing the main TV experience
    -Drive operator revenue and improved user experience through mobile broadband: -Optimize video delivery over LTE
    If any special needs to implement/deploy the function
    -This is a lightweight and standalone demo version of a complete End 2 End solution
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Dongyong Du
  Speaker introduction: 
record_19:
  Title: Game On Demand
  Start time: 11/29/2013 15:20
  Stop time: 11/29/2013 15:40
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Shaheer Jamal
  Speaker introduction: 
record_20:
  Title: Info on demand & eye ball tracking
  Start time: 11/29/2013 15:20
  Stop time: 11/29/2013 16:00
  Room: Wild-Center
  Abstract: |-
    Basic Functionality
    -Enables consumers to obtain additional information about the visual elements presented on the screen via a rich set of meta-data presented in a user-friendly way. -Enable consumers to share and discover similar visual elements in other content, or to purchase merchandising products related to those visual elements.
    Benefits to Customer
    -Encourage media consumption thru discovery and sharing of similar content.
    -Additional revenue channels in terms of content discovery, advertisement and cross selling of goods and content.
    -Increasing advertising values by providing hard data on consumer??s interested visual elements
    -Increase advertising values by pin-point of consumer attention (eye-tracker extension required)
    If any special needs to implement/deploy the function
    -About 2m distance from the eye-tracker for optimal operation of eye-tracker extension.
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 
  Speaker introduction: 
record_21:
  Title: Customer Care and Connected Car (UPG)
  Start time: 11/29/2013 16:00
  Stop time: 11/29/2013 16:20
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Arthur Wen
  Speaker introduction: 
record_22:
  Title: 'HD video conference across multi-terminals via MBB(LTE/HSPA) '
  Start time: 11/29/2013 16:20
  Stop time: 11/29/2013 16:40
  Room: Wild-Center
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: James Zhang
  Speaker introduction: 
record_23:
  Title: WiFi indoor Positioning
  Start time: 11/29/2013 14:00
  Stop time: 11/29/2013 14:20
  Room: E4F Coffee Area
  Abstract: "Basic Functionality\n-Provide WiFi based indoor positioning functionality.
    Client side (end-user) can request own location information in indoor environment
    on-demand, while server side (operator) can record these location information.
    \nBenefits to Customer\n-Service enabler of LBS solution in indoor environment,
    complementary to the outdoor positioning system.\n-Providing value added service
    to end-user, and other vertical chain (e.g. Mall, Airport, Office) based on the
    location data.\nIf any special needs to implement/deploy the function\n-WiFi Access
    Point Information. (Optimized WiFi APs deployment for positioning)\n-Collect and
    maintain the WiFi fingerprinting data in the target area to enhance accuracy."
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Edison Shu
  Speaker introduction: 
record_24:
  Title: 'M2M music band/weibo interaction/parking '
  Start time: 11/29/2013 14:30
  Stop time: 11/29/2013 15:00
  Room: E4F Coffee Area
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Clare Bao
  Speaker introduction: 
record_25:
  Title: Signalling Optimization in EPC
  Start time: 11/29/2013 15:00
  Stop time: 11/29/2013 15:30
  Room: A3F Gemini (18)
  Abstract: "Basic Functionality\n-Service based Paging\n-UE Signaling Control of
    misbehaving terminals \nBenefits to Customer\n-Save up to 85% paging messages,
    capacity which can be used for other purposes.\n-Distinguish and handle ??bad
    signaling?? and prioritize ??good?? signaling.\n-How much network load protection
    that can be provided by EPC, including EPC itself and also eNB\nIf any special
    needs to implement/deploy the function\n-Existing functionality in the SGSN-MME"
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: 'Robert Qu & Lasse Olsson '
  Speaker introduction: 
record_26:
  Title: Geo Redundancy in MME pool
  Start time: 11/29/2013 15:30
  Stop time: 11/29/2013 16:00
  Room: A3F Gemini (18)
  Abstract: "Basic Functionality\n-Is the functionality where UE information is replicated
    and ??stored else where?? in a pool environment\n-Allows an outage of one or many
    MMEs without major service impact on end users. \nBenefits to Customer\n-Virtually
    no service impact on end users in outage scenarios and assures extremely high
    availability of service to business partners.\n-Secures operational income and
    avoids negative market perception.\n -Use of sub-RANs saves transmission costs,
    since an eNodeB can select a nearby located MME. \nIf any special needs to implement/deploy
    the function\n-SGW shall support NTSR(Network Triggered Service Restoration) or
    keep bearer resource for a period of time when connected MME is not available\n-PGW
    shall keep bearer resource for a period of time when connected SGW is not available"
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Amy Li & Wei Zhang
  Speaker introduction: 
record_27:
  Title: Ericsson Cloud Management
  Start time: 11/29/2013 16:00
  Stop time: 11/29/2013 16:20
  Room: A3F Gemini (18)
  Abstract: 
  Column span: '3'
  Position: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: 
  Speakers: Howard Wang
  Speaker introduction: 
